apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coderag-git-ssh-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: coderag-cluster-secret-store
  target:
    name: coderag-git-ssh-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: id_rsa
      remoteRef:
        key: coderag/git-ssh
        property: id_rsa
    - secretKey: known_hosts
      remoteRef:
        key: coderag/git-ssh
        property: known_hosts
