[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
	ignore:on_event is deprecated, use lifespan event handlers instead\.:DeprecationWarning
	ignore:Support for class-based `Config` is deprecated, use ConfigDict instead\.:Warning
