apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cloud
  - ../../addons/redis
  - worker-deployment.yaml
patches:
  - path: patch-api-configmap-redis.yaml
  - path: patch-api-deployment-replicas.yaml
