apiVersion: v1
kind: Secret
metadata:
  name: coderag-api-secret
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  LLM_ANSWER_MODEL: ""
  LLM_VERIFIER_MODEL: ""
  EMBEDDING_MODEL: ""
  GEMINI_API_KEY: ""
  VERTEX_AI_PROJECT_ID: ""
  service-account.json: "{}"
  NEO4J_PASSWORD: "password"
